# Generated by Django 4.1 on 2022-08-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scuba_diving', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scubadiving',
            name='name',
        ),
    ]
