# Generated by Django 4.1 on 2022-08-10 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('scuba_diving', '0002_remove_scubadiving_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scubadiving',
            name='interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='interests.interest'),
        ),
    ]
