# Generated by Django 4.1 on 2022-08-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba_diving', '0003_scubadiving_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='scubadiving',
            name='best_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scubadiving',
            name='currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scubadiving',
            name='image2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scubadiving',
            name='image3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scubadiving',
            name='image4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scubadiving',
            name='image5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scubadiving',
            name='languages',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scubadiving',
            name='timezone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
