# Generated by Django 4.1 on 2022-08-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba_diving', '0004_scubadiving_best_time_scubadiving_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scubadiving',
            name='image6',
            field=models.URLField(blank=True, null=True),
        ),
    ]
